<a href="https://colab.research.google.com/github/malojighorpade/NewclassifiactionUsing-LSTM_RNN/blob/main/FakeNewsClassifiactionUsingLstmRnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/fake_news_dataset.csv')

In [ ]:
df

,title,author,text,label
0,Study Finds quantum computing Linked to Improv...,Amanda Martinez,"According to quarterly earnings reports, Amazo...",0
1,Congress Passes Bipartisan Bill on infrastructure,David Thompson,Scientists affiliated with NASA's Jet Propulsi...,0
2,"Local Community Raises $4.5,000 for youth educ...",Washington Bureau,"According to quarterly earnings reports, JPMor...",0
3,Scientists Discover traditional values Causes ...,AmericaFirst_News,The so-called experts have been lying to us ab...,1
4,Researchers Develop New Treatment for Alzheimer's,Christopher Lee,Scientists affiliated with NASA's Jet Propulsi...,0
...,...,...,...,...
19995,National Park Service Announces Expansion of T...,Stephanie Robinson,The Federal Reserve announced a policy adjustm...,0
19996,City Council Approves New red meat Infrastruct...,Sarah Johnson,"According to quarterly earnings reports, Amazo...",0
19997,George Soros Caught Funding the globalists to ...,GreatAwakeningNews,Citizens in multiple states are reporting that...,1
19998,the EU Preparing Secret Attack Using cash money,FreedomReporter,Sources close to the situation have revealed t...,1


In [ ]:
df.isnull()

,title,author,text,label
0,False,False,False,False
1,False,False,False,False
2,False,False,False,False
3,False,False,False,False
4,False,False,False,False
...,...,...,...,...
19995,False,False,False,False
19996,False,False,False,False
19997,False,False,False,False
19998,False,False,False,False


In [ ]:
df.shape

(20000, 4)

In [ ]:
X=df.drop('label',axis=1)

In [ ]:
y=df['label']

In [ ]:
X.shape

(19974, 3)

In [ ]:
import tensorflow as tf


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size=7000


In [ ]:
messages=X.copy()

In [ ]:
messages['text'][1]

"Scientists affiliated with NASA's Jet Propulsion Laboratory announced confirmation of previously undetected geological activity on Mars, opening new avenues for understanding planetary formation. Officials have not yet responded to requests for further comment."

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()


In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
corpus = []
for i in range(0, len(messages)):

    review = re.sub('[^a-zA-Z0-9]', ' ', messages['text'][i])
    review=review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)


In [ ]:
corpus

['accord quarterli earn report amazon exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat find subject peer review',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ mar open new avenu understand planetari format offici yet respond request comment',
 'accord quarterli earn report jpmorgan exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat addit data expect releas next quarter',
 'call expert lie us cash money begin thousand document obtain underground network confirm worst fear concern citizen mainstream media never report',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ europa open new avenu understand planetari format report made avail public onlin',
 'trade agreement sign japan australia expect reduc tariff agricultur export technolog good benefit industri nation next decad find subject peer review'

In [ ]:
onehot_repr=[one_hot(i,voc_size)for i in corpus]
onehot_repr

[[1538,
  4343,
  3714,
  108,
  6919,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  6420,
  2216,
  6080,
  6539],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  2469,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  4839,
  4762,
  1072,
  1898,
  2786],
 [1538,
  4343,
  3714,
  108,
  5576,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [6793,
  1950,
  636,
  496,
  5976,
  448,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  3977,
  459,
  292,
  108],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  6399,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  108,
  6556,
  3538,
  6038,
  1812],
 [4686,
  825,
  4016,
  5084,
  2495,
  31,
  5273,
  6932,
  2572,
  2687,
  500,
  290,
  5913,
  

In [ ]:
corpus[9]

'bipartisan group lawmak reach compromis agreement cybersecur legisl week negoti bill expect receiv vote full chamber end month find subject peer review'

In [ ]:
onehot_repr[9]

[2569,
 265,
 6295,
 1912,
 6049,
 825,
 4118,
 4156,
 1659,
 3284,
 6836,
 31,
 5824,
 4631,
 2478,
 851,
 248,
 2111,
 6420,
 2216,
 6080,
 6539]

In [ ]:
max_lenght=30
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=max_lenght)
print(embedded_docs)



[[   0    0    0 ... 2216 6080 6539]
 [   0    0    0 ... 1072 1898 2786]
 [   0    0    0 ... 3523 3020 5188]
 ...
 [   0    0    0 ... 3752 5710 5177]
 [   0    0    0 ... 4297 6808  621]
 [   0 5220 3882 ... 3523 3020 5188]]


In [ ]:
embedded_docs[90]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3338,
         24, 3179, 4097, 2430, 6104, 3843,  933, 6846, 3276, 4515, 2051,
       3926, 3717, 1217, 5078, 5382, 6605, 1007, 4887], dtype=int32)

In [ ]:
model = Sequential()
embedding_vector_features=40
model.add(Embedding(voc_size, embedding_vector_features,input_shape=(max_lenght,)))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 30, 40)         │       280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 336,501 (1.28 MB)

 Trainable params: 336,501 (1.28 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import numpy as np
X_final1=np.array(embedded_docs)
y_final2=np.array(y)


In [ ]:
X_final1.shape,y_final2.shape

((20000, 30), (20000,))

In [ ]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_final1, y_final2, test_size=0.33, random_state=50
)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 13s 60ms/step - accuracy: 1.0000 - loss: 5.4828e-06 - val_accuracy: 1.0000 - val_loss: 5.0972e-06
Epoch 2/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 12s 59ms/step - accuracy: 1.0000 - loss: 4.7416e-06 - val_accuracy: 1.0000 - val_loss: 4.4175e-06
Epoch 3/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - accuracy: 1.0000 - loss: 4.1172e-06 - val_accuracy: 1.0000 - val_loss: 3.8433e-06
Epoch 4/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 11s 53ms/step - accuracy: 1.0000 - loss: 3.5880e-06 - val_accuracy: 1.0000 - val_loss: 3.3553e-06
Epoch 5/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 14s 66ms/step - accuracy: 1.0000 - loss: 3.1368e-06 - val_accuracy: 1.0000 - val_loss: 2.9374e-06
Epoch 6/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 1.0000 - loss: 2.7501e-06 - val_accuracy: 1.0000 - val_loss: 2.5790e-06
Epoch 7/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 14s 67ms/step - accuracy: 1.0000 - loss: 2.4172e-06 - val_accuracy: 1.0000 - val_loss: 2.2696e-06
Epoch 8/10
 28/210 ━━━━━━━━━━━━━━━

KeyboardInterrupt: 

In [ ]:
model.evaluate(X_test, y_test)

207/207 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 1.0000 - loss: 2.2303e-06


[2.2303479454421904e-06, 1.0]

In [ ]:
import numpy as np
print(np.unique(y_final, return_counts=True))

(array([0, 1]), array([10043,  9957]))


In [ ]:
print(set(map(str, X_train)) & set(map(str, X_test)))

{'[   0    0    0    0    0    0    0 3893 2855 6292 4328 2804 6440 4501\n 4232 3396 6096 3432 2215 6399 1087 1614 5679 4080 6673 2766 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 2292 3401  806\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0 3172 2214 3843 4097 2430  529\n 2939  933 5076 4681 4304 3547 1331 5177 1412 3677 3430 3604   24 3752\n 5710 5177]', '[   0    0    0    0    0    0    0 3752 5084 2737 5626 6420 2314 3697\n 3777 2877 2719 6367 3717 5110 3892 1387 5983 6432  862 4839 4762 1072\n 1898 2786]', '[   0    0    0    0    0    0    0    0    0    0 3338   24 3179 4133\n 6104 3843 5560 6846 3276 4515 2051 3926 3717 1217 5078 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 2854 6104 3843 1057 6846 3276 4515 2051 3926 3717 1217 5078 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0    

In [ ]:
# Check overlap between train and test
overlap = set(map(str, X_train)) & set(map(str, X_test))
print(len(overlap))